# shellcheck shell=bash
# meshvpn - out-of-band key workflow helper
# Maintainer: Cognis Digital
# License: COCL 1.0
#
# meshvpn NEVER generates or stores private keys itself. This module only
# EMITS a helper script that an operator runs OUT OF BAND (on a trusted host,
# outside version control) to mint one keypair per node with the real `wg`
# tooling. The generated script writes *.private / *.public files that the
# bundled .gitignore already blocks from being committed.

# Print a runnable key-minting helper for the parsed fleet to stdout.
# The operator saves it, reviews it, and runs it themselves. meshvpn does not
# execute it and does not touch the resulting key material.
mv_keygen_script() {
    if [ "$MV_NODE_COUNT" -eq 0 ]; then
        mv_err "no nodes; parse a config first"
        return 2
    fi
    local i
    cat <<'HEADER'
#!/usr/bin/env sh
# meshvpn key-minting helper (RUN THIS OUT OF BAND on a trusted host).
# Generated by `meshvpn keygen`. meshvpn itself never handled any key material.
#
# Requires WireGuard tools: `wg` must be on PATH.
# Produces <node>.private and <node>.public per node in the current directory.
# Do NOT commit *.private. Inject private keys via your secret store.
set -eu
if ! command -v wg >/dev/null 2>&1; then
    echo "error: 'wg' not found. Install WireGuard tools." >&2
    exit 1
fi
umask 077
HEADER
    for ((i = 0; i < MV_NODE_COUNT; i++)); do
        local stem
        stem="$(_mv_safe_stem "${MV_NODE_NAME[i]}")"
        printf 'echo "minting keypair for %s..."\n' "${MV_NODE_NAME[i]}"
        printf 'wg genkey | tee %s.private | wg pubkey > %s.public\n' "$stem" "$stem"
    done
    cat <<'FOOTER'
echo "done. Public keys are in *.public; keep *.private secret and out of git."
echo "Replace the <FILL_PUBKEY:...> and <FILL_FROM_SECRET:...> placeholders in"
echo "the generated wgN.conf files with the matching key material."
FOOTER
    return 0
}
